# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calendar_contains <- function(calendar, date) {
    .Call('_statarber_calendar_contains', PACKAGE = 'statarber', calendar, date)
}

calendar_gt <- function(calendar, date) {
    .Call('_statarber_calendar_gt', PACKAGE = 'statarber', calendar, date)
}

calendar_gte <- function(calendar, date, n) {
    .Call('_statarber_calendar_gte', PACKAGE = 'statarber', calendar, date, n)
}

calendar_lte <- function(calendar, date, n) {
    .Call('_statarber_calendar_lte', PACKAGE = 'statarber', calendar, date, n)
}

calendar_lt <- function(calendar, date) {
    .Call('_statarber_calendar_lt', PACKAGE = 'statarber', calendar, date)
}

unlock_environment <- function(env) {
    .Call('_statarber_unlock_environment', PACKAGE = 'statarber', env)
}

